[package]
name = "test-rust"
version = "0.1.0"
authors = ["aksiksi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.5"

[build-dependencies]
bindgen = "0.51.1"
